env:
  CHART_NAME: standard-service
  WORKING_DIRECTORY: ./charts

name: Build & Push Helm chart

on:
  push:
    branches: 
    - "main"
    paths: # This is equal as WORKING_DIRECTORY/CHART_NAME, but has to be hardcoded because of workflow's workflow https://stackoverflow.com/questions/68336078/how-to-use-env-variable-on-workflow-level-github-actions
     - charts/standard-service/**
  pull_request:
    paths: # This is equal as WORKING_DIRECTORY/CHART_NAME, but has to be hardcoded because of workflow's workflow https://stackoverflow.com/questions/68336078/how-to-use-env-variable-on-workflow-level-github-actions
     - charts/standard-service/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGEHUB_URL: ${{ secrets.IMAGEHUB_URL}}
      IMAGEHUB_USERNAME: ${{ secrets.IMAGEHUB_USERNAME}}
      IMAGEHUB_PASSWORD: ${{ secrets.IMAGEHUB_PASSWORD}}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Push a chart to a registry
      - name: Package & Push
        id: hello
        uses: ./.github/actions/helm-push
